---
machine:
  image: "ubuntu/xenial64"
  memory: "1024"
  cpus: "2"

nodes:
  - ip: 10.0.0.2
    public_ip: 192.168.99.102
    role: master
    disks:
      - size: 2 # Size in Gb
#  - ip: 10.0.0.3
#    role: master
#    disks:
#      - size: 2
  - ip: 10.0.0.4
    public_ip: 192.168.99.104
    role: slave
    disks:
      - size: 1
#  - ip: 10.0.0.5
#    role: slave
#    disks:
#      - size: 1
#  - ip: 10.0.0.6
#    role: slave
#    disks:
#      - size: 1
#  - ip: 10.0.0.7
#    role: slave
#    disks:
#      - size: 1
