---
machine:
  image: "ubuntu/xenial64"
  memory: "2048"
  cpus: "2"

nodes:
  - ip: 192.168.0.102
    role: master
    disks:
      - size: 2 # Size in Gb
  - ip: 192.168.0.103
    role: master
    disks:
      - size: 2
  - ip: 192.168.0.104
    role: slave
    disks:
      - size: 1
  - ip: 192.168.0.105
    role: slave
    disks:
      - size: 1
#  - ip: 10.0.0.6
#    role: slave
#    disks:
#      - size: 1
#  - ip: 10.0.0.7
#    role: slave
#    disks:
#      - size: 1
