---
machine:
  image: "ubuntu/xenial64"
  memory: "1024"
  cpus: "2"

nodes:
  - ip: 10.0.0.2
    role: master
  - ip: 10.0.0.3
    role: master
  - ip: 10.0.0.4
    role: slave
    disks:
      - size: 1 # Size in Gb
  - ip: 10.0.0.5
    role: slave
    disks:
      - size: 1

