apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: glusterfs-simple-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: glusterfs-simple-provisioner
    spec:
      serviceAccount: glfs-provisioner
      containers:
        - image: "quay.io/external_storage/glusterfs-simple-provisioner:v2.1.0-k8s1.11"
          name: glusterfs-simple-provisioner
