---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: glusterfs-simple
provisioner: gluster.org/glusterfs-simple
reclaimPolicy: Retain
parameters:
  forceCreate: "true"
  volumeType: "replica 3"
  brickrootPaths: "192.168.0.102:/etc/kubernetes/bricks/brick0,192.168.0.103:/etc/kubernetes/bricks/brick0,192.168.0.104:/etc/kubernetes/bricks/brick0,192.168.0.105:/etc/kubernetes/bricks/brick0,192.168.0.102:/etc/kubernetes/bricks/brick1,192.168.0.103:/etc/kubernetes/bricks/brick1,192.168.0.104:/etc/kubernetes/bricks/brick1,192.168.0.105:/etc/kubernetes/bricks/brick1,192.168.0.102:/etc/kubernetes/bricks/brick2,192.168.0.103:/etc/kubernetes/bricks/brick2,192.168.0.104:/etc/kubernetes/bricks/brick2,192.168.0.105:/etc/kubernetes/bricks/brick2"
