---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: glusterfs-simple
provisioner: gluster.org/glusterfs-simple
reclaimPolicy: Retain
parameters:
  forceCreate: "true"
  volumeType: "replica 2"
  brickrootPaths: "10.0.0.2:/etc/kubernetes/bricks/brick0,10.0.0.4:/etc/kubernetes/bricks/brick0,10.0.0.2:/etc/kubernetes/bricks/brick1,10.0.0.4:/etc/kubernetes/bricks/brick1"

