apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    app: webserver
  ports:
    - name: wiki
      port: 8080
      targetPort: 8080
    - name: ecommerce
      port: 8081
      targetPort: 8081
  clusterIP: 10.96.80.80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: kajachuan/kero-webserver
        ports:
        - containerPort: 8080
        - containerPort: 8081
