apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: webserver
spec:
  selector:
    app: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 10.96.80.80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: kajachuan/kero-webserver
        ports:
        - containerPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: webserver-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/add-base-url: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: kerotest.ddns.net
    http:
      paths:
      - backend:
          serviceName: webserver
          servicePort: 80
  - host: kero.ecommerce.io
    http:
      paths:
      - backend:
          serviceName: webserver
          servicePort: 80
  tls:
    - hosts:
        - kerotest.ddns.net
      secretName: wiki.tls
