apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${PV}-tmp
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-simple"
    pv.kubernetes.io/provisioned-by: gluster.org/glusterfs-simple
spec:
  capacity:
    storage: ${VOLUME_SIZE}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  claimRef:
    namespace: default
    name: ${PVC}-tmp
  glusterfs:
    endpoints: glusterfs-simple-${PVC}
    path: ${PV}
