apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC}-tmp
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-simple"
spec:
  volumeName: ${PV}-tmp
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: ${VOLUME_SIZE}
