#! /bin/bash

function usage() {
    echo
    echo "Starts a new vnc server for a specific user"
    echo
    echo -e "\tusage: $(basename "$0") username user_id"
    echo
    exit 1
}

if [[ -z $1 || -z $2 ]]; then
    usage
fi

export VNC_USERNAME=$1
export VNC_USERID=$2

echo -n "Password for ${VNC_USERNAME}:"
read -sr VNC_PASS
echo

## TODO: validate password

export VNC_PW="${VNC_PASS}"

export VNC_HTTP_PORT=$((31001 + VNC_USERID))
export VNC_PORT=$((30001 + VNC_USERID))
echo "Connect to port: ${VNC_HTTP_PORT}"

## TODO: absolute path for template (maybe embedded here?)
envsubst < template.yaml | kubectl apply -f -
