kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: home-claim-${VNC_USERNAME}
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-simple"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
