#! /bin/bash

set +x

envsubst < $KERO_HOME/services/metallb/metallb.yaml | kubectl apply -f -
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

NODE_COUNT="$(kubectl get nodes --no-headers | awk '{print $3}' | wc -l)"

count="$(kubectl get pods --no-headers -n metallb-system | grep speaker | awk '{print $3}' | grep Running | wc -l)"
while [ "$count" -lt "$NODE_COUNT" ]; do
  echo "Waiting for MetalLB: $count / $NODE_COUNT"
  sleep 5
  count="$(kubectl get pods --no-headers -n metallb-system | grep speaker | awk '{print $3}' | grep Running | wc -l)"
done

envsubst < $KERO_HOME/services/metallb/config.yaml | kubectl apply -f -

echo "MetalLB is now Running: $count / $NODE_COUNT"
