#! /bin/bash

set +x

envsubst < $KERO_HOME/services/cert-manager/cert-manager-legacy.yaml | kubectl apply --validate=false -f -

POD_COUNT=3

count="$(kubectl get pods --no-headers -n cert-manager | awk '{print $3}' | grep Running | wc -l)"
while [ "$count" -lt "$POD_COUNT" ]; do
  echo "Waiting for cert-manager: $count / $POD_COUNT"
  sleep 5
  count="$(kubectl get pods --no-headers -n cert-manager | awk '{print $3}' | grep Running | wc -l)"
done

echo "Waiting for webhook"
sleep 20
envsubst < $KERO_HOME/services/cert-manager/issuer.yaml | kubectl apply -f -

echo "cert-manager is now Running: $count / $POD_COUNT"
