#! /bin/bash

set +x

echo "Please run me on your host system, I need to ssh into every node!"

read -p "You are about to COMPLETELY ERASE the glusterfs cluster. All data will be lost. Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

vagrant ssh node-1 -c " \
    sudo kubectl delete daemonset glusterfs; \
    sudo kubectl delete sc glusterfs-simple; \
    sudo kubectl delete deployment glusterfs-simple-provisioner; \
    sudo kubectl delete pvc --all; \
    sudo kubectl delete pv --all;"

for node in node-{1,2,3,4,5,6}; do
    vagrant ssh $node -c " \
        sudo umount /etc/kubernetes/{brick,bricks}; \
        sudo rmdir /etc/kubernetes/{brick,bricks}; \
        sudo $KERO_HOME/scripts/create-bricks; \
        sudo mkdir -p /etc/kubernetes/bricks/brick0 /etc/kubernetes/bricks/brick1  /etc/kubernetes/bricks/brick2; \
        sudo rm -rf /var/lib/misc/glusterfsd; \
        sudo rm -rf /etc/glusterfs; \
        sudo rm -rf /var/lib/glusterd;"
done

echo "You are free of gluster, for now..."
