#! /bin/bash

set +x

if [[ -z $1 ]]; then
  echo "You must give a node name to destroy."
  exit 1
fi

NODE=$1

## Add a little flavor
ADJ=("great" "miserable" "pathetic" "heroic" "short" "promiscuous")
ADJ_LEN=${#ADJ[*]}
RANDOM=$(date +%N)
FLAVOR=${ADJ[$RANDOM % $ADJ_LEN]}

read -p "You are about to end the ${FLAVOR} life of ${NODE}. Are you sure? " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    exit 0
fi

kubectl drain $NODE --ignore-daemonsets --grace-period=0 --delete-local-data --force
kubectl delete node $NODE
kubectl get pods -n kube-system -o wide | grep $NODE | cut -f1 -d' '| xargs kubectl delete pod -n kube-system --force --grace-period=0

NODE_CODE=$(sudo -i etcdctl --insecure-skip-tls-verify member list | grep $NODE | cut -d "," -f 1)
sudo -i etcdctl --insecure-skip-tls-verify member remove $NODE_CODE

## Add even more flavor
ADJ=("destroyed" "killed" "pulverized" "executed" "carried to heaven")
ADJ_LEN=${#ADJ[*]}
FLAVOR=${ADJ[$RANDOM % $ADJ_LEN]}

echo "Node ${NODE} was ${FLAVOR} successfully."
