#! /bin/bash

# Install Kubeadm
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -qy kubernetes-cni=0.8.6-00 kubelet=1.18.6-00 kubeadm=1.18.6-00 kubectl=1.18.6-00
apt-get install -y glusterfs-client
apt-mark hold kubelet kubeadm kubectl
