#! /bin/bash

# Install Kubeadm
apt-get update && apt-get install -y apt-transport-https curl
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
apt-get update
apt-get install -qy kubernetes-cni=0.7.5-00 kubelet=1.14.0-00 kubeadm=1.14.0-00 kubectl=1.14.0-00
add-apt-repository ppa:gluster/glusterfs-4.1
apt-get install -y glusterfs-client=4.1.10-ubuntu1~xenial1
apt-mark hold kubelet kubeadm kubectl
