#!/bin/bash

set +x

echo "Pulling all docker images. This process could take some minutes..."

# VNC image (remote desktop service)
sudo docker pull juanfresia/taller3-test-vnc

# GlusterFS images (shared file system service)
sudo docker pull gluster/gluster-centos:latest
sudo docker pull quay.io/external_storage/glusterfs-simple-provisioner:latest

# LDAP images (users CRUD service)
sudo docker pull osixia/phpldapadmin:0.8.0
sudo docker pull kajachuan/openldap-postfix-book

# Mail server
sudo docker pull solidnerd/rainloop
sudo docker pull tvial/docker-mailserver:latest

# Desktop spawner image (foreign access service)
sudo docker pull juanfresia/desk-spawner:0.0.5

# Node stopper (for monitoring)
sudo docker pull juanfresia/node-stopper:0.0.2

echo "Pulling process completed!"
