#! /bin/bash

function usage() {
    echo
    echo "Starts a new vnc server for a specific user"
    echo
    echo -e "\tusage: $(basename "$0") userid "
    echo
    exit 1
}

if [[ -z $1 ]]; then
    usage
fi

export VNC_USERNAME=$1

echo -n "Password for admin:"
read -sr VNC_PASS
echo

## Using LDAP to validate password and get user id
LDAP_CLUSTER_IP=$(kubectl get svc | grep ldap-svc | awk {'print $3'})
VNC_USERID=$(curl -s "ldap://${LDAP_CLUSTER_IP}:389/uid=${VNC_USERNAME},ou=People,dc=fiuba,dc=com" -u "cn=admin,dc=fiuba,dc=com":$VNC_PASS | grep "uidNumber:" | awk '{print $2}')
VNC_GROUP=$(curl -s "ldap://${LDAP_CLUSTER_IP}:389/dc=fiuba,dc=com?PosixGroup?sub?(memberUid=${VNC_USERNAME})" -u "cn=admin,dc=fiuba,dc=com":$VNC_PASS | grep "cn:" | awk '{print $2}')

if [[ -z "$VNC_USERID" ]]; then
    echo "Error: Invalid credentials"
    exit 1
fi

export VNC_PW="${VNC_PASS}"

export VNC_HTTP_PORT=$((31001 + VNC_USERID))
export VNC_PORT=$((30001 + VNC_USERID))

export VNC_GROUP

envsubst < $KERO_HOME/vnc/template.yaml | kubectl apply -f -
envsubst < $KERO_HOME/vnc/pvc-template.yaml | kubectl apply -f -
kubectl apply -f $KERO_HOME/vnc/pvc-shared.yaml

VNC_STATUS=$(kubectl get pods | grep "vnc-${VNC_USERNAME}" | awk '{print $3}')
while [ $VNC_STATUS != "Running" ]; do
    echo "Waiting for VNC deployment (status: ${VNC_STATUS})"
    sleep 7
    VNC_STATUS=$(kubectl get pods | grep "vnc-${VNC_USERNAME}" | awk '{print $3}')
done

VNC_IP=$(kubectl get svc --no-headers | grep "vnc-svc-${VNC_USERNAME}" | awk '{print $3}')
sleep 8
echo "Connect to ${VNC_IP}"
