kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: group-claim-${VNC_GROUP}
  annotations:
    volume.beta.kubernetes.io/storage-class: "glusterfs-simple"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi