apiVersion: apps/v1
kind: Deployment
metadata:
  name: desk-spawner
  labels:
    application: desk-spawner
spec:
  replicas: 1
  selector:
    matchLabels:
      application: desk-spawner
  template:
    metadata:
      labels:
        application: desk-spawner
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: desk-spawner
        image: juanfresia/desk-spawner:0.0.5
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: ${KERO_HOME}
          name: vnc
        - mountPath: /etc/kubernetes
          name: config
        env:
        - name: KUBECONFIG
          value: /etc/kubernetes/admin.conf
      volumes:
      - name: vnc
        hostPath:
          path: ${KERO_HOME}
          type: Directory
      - name: config
        hostPath:
          path: /etc/kubernetes
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    application: desk-spawner
  name: desk-spawner-svc
spec:
  externalName: desk-spawner-svc
  type: NodePort
  ports:
  - name: admin-panel-tcp
    protocol: TCP
    port: 80
    targetPort: 5000
  selector:
    application: desk-spawner
---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
 name: desk-spawner-ingress
 annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
 rules:
 - host: kero.desk-spawner.io
   http:
     paths:
     - path: /
       backend:
         serviceName: desk-spawner-svc
         servicePort: 80
